# -*- coding: utf-8 -*-
"""ppecc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hk6tTuu4ZXIsTttJSlPZfxYbjYK3vR77
"""

import pandas as pd 

ubicaciones = pd.read_csv('https://github.com/jkmilop/deforest/blob/main/ubicacion.csv?raw=true') 
propietarios = pd.read_csv('https://github.com/jkmilop/deforest/blob/main/propietarios.csv?raw=true') 
zonas = pd.read_csv('https://github.com/jkmilop/deforest/blob/main/zona.csv?raw=true')